# Generated by Django 5.1.3 on 2024-12-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_stock_producto_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Inventario',
        ),
    ]
