# Generated by Django 5.1.3 on 2024-12-05 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_imagen_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagenes_producto',
        ),
        migrations.AddField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='store.producto'),
        ),
    ]
