# Generated by Django 5.1.3 on 2024-12-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_producto_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagenes_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/producto/'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
